using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using RimWorld;
using UnityEngine;
using Verse;

namespace OMWPersonaDevouringPawn
{
    public sealed class PersonaDevouringSettings : ModSettings
    {
        public string lastDumpStatus;
        public bool logAdaptorTriggers;

        public override void ExposeData()
        {
            Scribe_Values.Look(ref lastDumpStatus, "lastDumpStatus");
            Scribe_Values.Look(ref logAdaptorTriggers, "logAdaptorTriggers", false);
        }

        public void DoWindowContents(Rect inRect, ModContentPack content)
        {
            Listing_Standard listing = new Listing_Standard();
            listing.Begin(inRect);
            listing.Label("OMW_SettingsDumpDescription".Translate());
            listing.Gap(12f);
            listing.CheckboxLabeled(
                "OMW_SettingsLogAdaptorTriggers".Translate().ToString(),
                ref logAdaptorTriggers,
                "OMW_SettingsLogAdaptorTriggersDescription".Translate().ToString());
            listing.Gap(12f);

            if (listing.ButtonText("OMW_SettingsDumpButton".Translate().ToString()))
            {
                try
                {
                    string path = PersonaTraitDump.Write(content);
                    lastDumpStatus = "OMW_SettingsDumpSuccess".Translate(path.Named("PATH")).ToString();
                }
                catch (Exception ex)
                {
                    lastDumpStatus = "OMW_SettingsDumpFailure".Translate(ex.Message.Named("ERROR")).ToString();
                    Log.Error($"[Persona Trait Devourer] Could not dump loaded WeaponTraitDefs: {ex}");
                }
            }

            if (!lastDumpStatus.NullOrEmpty())
            {
                listing.Gap(12f);
                listing.Label(lastDumpStatus);
            }
            listing.End();
        }
    }

    public static class PersonaTraitDump
    {
        public static string Write(ModContentPack content)
        {
            string docsDirectory = Path.Combine(content.RootDir, "docs");
            Directory.CreateDirectory(docsDirectory);
            string path = Path.Combine(docsDirectory, "WeaponTraits.md");
            File.WriteAllText(path, BuildMarkdown(), Encoding.UTF8);
            return path;
        }

        private static string BuildMarkdown()
        {
            var output = new StringBuilder();
            output.AppendLine("# Persona Weapon Traits");
            output.AppendLine();
            output.AppendLine("<!-- Generated by [OMW] Persona Trait Devourer settings. Documentation only. -->");
            output.AppendLine();

            IEnumerable<IGrouping<string, WeaponTraitDef>> groups = DefDatabase<WeaponTraitDef>.AllDefsListForReading
                .GroupBy(SourceName)
                .OrderBy(group => group.Key, StringComparer.OrdinalIgnoreCase);
            foreach (IGrouping<string, WeaponTraitDef> group in groups)
            {
                output.AppendLine($"## {EscapeMarkdown(group.Key)}");
                output.AppendLine();
                foreach (string category in new[] { "Supported", "Unsupported", "Blacklisted" })
                {
                    List<WeaponTraitDef> traits = group
                        .Where(trait => TraitCategory(trait) == category)
                        .OrderBy(trait => trait.defName, StringComparer.OrdinalIgnoreCase)
                        .ToList();
                    if (traits.Count == 0)
                    {
                        continue;
                    }

                    output.AppendLine($"### {category}");
                    output.AppendLine();
                    foreach (WeaponTraitDef trait in traits)
                    {
                        TraitDisposition disposition = TraitAdapters.Classify(trait, out _);
                        bool unsupported = disposition == TraitDisposition.Unsupported;
                        bool blacklisted = PersonaDevouringTraitRules.IsBlacklisted(trait);
                        output.AppendLine($"#### {EscapeMarkdown(trait.defName)}");
                        output.AppendLine();
                        output.AppendLine(string.IsNullOrWhiteSpace(trait.description)
                            ? "No description provided."
                            : EscapeMarkdownParagraph(trait.description));
                        output.AppendLine();
                        output.AppendLine($"- **Label:** {EscapeMarkdown(trait.label ?? trait.defName)}");
                        output.AppendLine($"- **Blacklisted:** {(blacklisted ? "Yes" : "No")}");
                        output.AppendLine($"- **Unsupported:** {(unsupported ? "Yes" : "No")}");
                        output.AppendLine($"- **Adapter mechanism list:** {EscapeMarkdown(AdapterMechanism(trait))}");
                        output.AppendLine();
                    }
                }
            }

            return output.ToString();
        }

        private static string SourceName(WeaponTraitDef trait)
        {
            return trait?.modContentPack?.Name.NullOrEmpty() != false
                ? "Core"
                : trait.modContentPack.Name;
        }

        private static string TraitCategory(WeaponTraitDef trait)
        {
            TraitDisposition disposition = TraitAdapters.Classify(trait, out _);
            if (PersonaDevouringTraitRules.IsBlacklisted(trait) || disposition == TraitDisposition.Ignored)
            {
                return "Blacklisted";
            }
            return disposition == TraitDisposition.Unsupported ? "Unsupported" : "Supported";
        }

        private static string AdapterMechanism(WeaponTraitDef trait)
        {
            var mechanisms = new List<string>();
            if (PersonaDevouringTraitRules.IsBlacklisted(trait))
            {
                mechanisms.Add("blacklisted");
            }
            if (trait.equippedStatOffsets?.Count > 0)
            {
                mechanisms.Add("equipped stat offsets");
            }
            if (trait.equippedHediffs?.Count > 0)
            {
                mechanisms.Add("equipped hediff stages");
            }
            if (trait.bondedHediffs?.Count > 0)
            {
                mechanisms.Add("bonded hediff stages");
            }
            if (trait.bondedThought != null)
            {
                mechanisms.Add("bonded thought");
            }
            if (trait.killThought != null)
            {
                mechanisms.Add("on-kill thought");
            }
            if (trait.defName == "PsyfocusMeditationBonus" || trait.defName == "OnKill_PsyfocusGain")
            {
                mechanisms.Add("on-kill psyfocus");
            }
            if (trait.workerClass != null && trait.workerClass.FullName != "RimWorld.WeaponTraitWorker")
            {
                mechanisms.Add($"worker class `{trait.workerClass.FullName}`");
            }
            foreach (DefModExtension extension in trait.modExtensions ?? Enumerable.Empty<DefModExtension>())
            {
                string extensionName = extension?.GetType().FullName ?? string.Empty;
                if (extensionName == "MorePersonaTraits.Extensions.WeaponTraitOnHitExtension")
                {
                    mechanisms.Add("More Persona Traits on-hit extension");
                }
                else if (extensionName == "MorePersonaTraits.Extensions.WeaponTraitOnKillExtension")
                {
                    mechanisms.Add("More Persona Traits on-kill extension");
                }
            }
            return mechanisms.Count == 0 ? "none" : string.Join("; ", mechanisms.Distinct());
        }

        private static string EscapeMarkdownParagraph(string value)
        {
            return (value ?? string.Empty).Replace("\\r", " ").Replace("\\n", " ").Trim();
        }

        private static string EscapeMarkdown(string value)
        {
            return (value ?? string.Empty)
                .Replace("\\", "\\\\")
                .Replace("`", "\\`")
                .Replace("*", "\\*")
                .Replace("_", "\\_")
                .Replace("[", "\\[")
                .Replace("]", "\\]")
                .Replace("#", "\\#");
        }
    }
}
