using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using RimWorld;
using UnityEngine;
using Verse;

namespace OMWPersonaDevouringPawn
{
    public sealed class PersonaDevouringSettings : ModSettings
    {
        public string lastDumpStatus;
        public bool logAdaptorTriggers;

        public override void ExposeData()
        {
            Scribe_Values.Look(ref lastDumpStatus, "lastDumpStatus");
            Scribe_Values.Look(ref logAdaptorTriggers, "logAdaptorTriggers", false);
        }

        public void DoWindowContents(Rect inRect, ModContentPack content)
        {
            Listing_Standard listing = new Listing_Standard();
            listing.Begin(inRect);
            listing.Label("OMW_SettingsDumpDescription".Translate());
            listing.Gap(12f);
            listing.CheckboxLabeled(
                "OMW_SettingsLogAdaptorTriggers".Translate().ToString(),
                ref logAdaptorTriggers,
                "OMW_SettingsLogAdaptorTriggersDescription".Translate().ToString());
            listing.Gap(12f);

            if (listing.ButtonText("OMW_SettingsDumpButton".Translate().ToString()))
            {
                try
                {
                    string path = PersonaTraitDump.Write(content);
                    lastDumpStatus = "OMW_SettingsDumpSuccess".Translate(path.Named("PATH")).ToString();
                }
                catch (Exception ex)
                {
                    lastDumpStatus = "OMW_SettingsDumpFailure".Translate(ex.Message.Named("ERROR")).ToString();
                    Log.Error($"[Persona Trait Devourer] Could not dump loaded WeaponTraitDefs: {ex}");
                }
            }

            if (!lastDumpStatus.NullOrEmpty())
            {
                listing.Gap(12f);
                listing.Label(lastDumpStatus);
            }
            listing.End();
        }
    }

    public static class PersonaTraitDump
    {
        public static string Write(ModContentPack content)
        {
            string docsDirectory = Path.Combine(content.RootDir, "docs");
            Directory.CreateDirectory(docsDirectory);
            string path = Path.Combine(docsDirectory, "WeaponTraitDefs.xml");
            File.WriteAllText(path, BuildXml(), Encoding.UTF8);
            return path;
        }

        private static string BuildXml()
        {
            var output = new StringBuilder();
            output.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            output.AppendLine("<!-- Generated by [OMW] Persona Trait Devourer settings. Documentation only. -->");
            output.AppendLine("<WeaponTraitDefsDump>");

            foreach (WeaponTraitDef trait in DefDatabase<WeaponTraitDef>.AllDefsListForReading.OrderBy(x => x.defName))
            {
                TraitDisposition disposition = TraitAdapters.Classify(trait, out string reason);
                bool suppressed = PersonaDevouringTraitRules.IsBlacklisted(trait);
                List<string> overrides = PersonaDevouringTraitRules.TraitsOverriddenBy(trait.defName).ToList();
                List<string> overriddenBy = PersonaDevouringTraitRules.TraitsThatOverride(trait.defName).ToList();
                string status = suppressed ? "suppressed" : disposition == TraitDisposition.Unsupported ? "unsupported" : disposition == TraitDisposition.Supported ? "devourable" : "ignored";
                string source = trait.modContentPack?.PackageIdPlayerFacing ?? trait.modContentPack?.Name ?? "Core";

                output.AppendLine($"  <WeaponTraitDef defName=\"{Escape(trait.defName)}\" label=\"{Escape(trait.label)}\" status=\"{status}\" suppressed=\"{suppressed.ToString().ToLowerInvariant()}\" unsupported=\"{(disposition == TraitDisposition.Unsupported).ToString().ToLowerInvariant()}\" source=\"{Escape(source)}\">");
                if (!reason.NullOrEmpty())
                {
                    output.AppendLine($"    <classificationReason>{Escape(reason)}</classificationReason>");
                }
                output.AppendLine("    <overrides>");
                foreach (string overridden in overrides)
                {
                    output.AppendLine($"      <defName>{Escape(overridden)}</defName>");
                }
                output.AppendLine("    </overrides>");
                output.AppendLine("    <overriddenBy>");
                foreach (string replacement in overriddenBy)
                {
                    output.AppendLine($"      <defName>{Escape(replacement)}</defName>");
                }
                output.AppendLine("    </overriddenBy>");
                output.AppendLine("  </WeaponTraitDef>");
            }

            output.AppendLine("</WeaponTraitDefsDump>");
            return output.ToString();
        }

        private static string Escape(string value)
        {
            return SecurityElement.Escape(value ?? string.Empty) ?? string.Empty;
        }
    }
}
